# Deployment pipelines exercise 3.1

name: deployment_pipelines

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]    # Triggers the workflow on push request events but only for the "main" branch
  
  workflow_dispatch:        # Allows you to run this workflow manually from the Actions tab
env:                        #Dockerhub tokens 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # 

jobs:                       # A workflow run is made up of one or more jobs that can run sequentially or in parallel

  build:
    runs-on: ubuntu-latest            # The type of runner that the job will run on
    steps:                            # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Checkout code
      - uses: actions/checkout@v3     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ernoserna/nodejs-pipeline:latest
